framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        packages:
            local:
            s3:
                base_urls: '%env(S3_PUBLIC_URL)%'
