# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md

services:
    app.flysytem.http_client_adapter:
        class: App\Flysystem\HttpClientAdapter
        autowire: true
        arguments:
            $options: { base_uri: '%env(AWS_S3_URL)%' }

flysystem:
    storages:
        s3.storage.reader:
            adapter: 'app.flysytem.http_client_adapter'
            options:
                bucket: '%env(AWS_S3_BUCKET_NAME)%'

        users.storage:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                prefix: 'uploads/users'

        events.storage:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                prefix: 'uploads/documents'

        thumbs.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/thumbs'

        assets.storage.reader:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public'

# In production we disable thumb storage because it's handled by cloudfront
when@prod:
    flysystem:
        storages:
            thumbs.storage:
                adapter: 'memory'
