# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        s3.storage.reader:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                bucket: "%env(AWS_S3_BUCKET_NAME)%"

        users.storage:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                bucket: "%env(AWS_S3_BUCKET_NAME)%"
                prefix: '/uploads/users'

        events.storage:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                bucket: "%env(AWS_S3_BUCKET_NAME)%"
                prefix: '/uploads/documents'

        thumbs.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/thumbs'

        assets.storage.reader:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public'
