#HTTP Cache
fos_http_cache:
    tags:
        enabled: true

    proxy_client:
        varnish:
            tag_mode: 'purgekeys'
            tags_header: 'xkey'
            http:
                servers:
                    - '%env(VARNISH_URL)%'
                base_url: '%env(APP_URL)%'
