#HTTP Cache
fos_http_cache:
    tags:
        enabled: true
        annotations:
            enabled: false

    proxy_client:
        varnish:
            http:
                servers:
                    - varnish
                base_url: '%env(APP_URL)%'
