#RabbitMQ
old_sound_rabbit_mq:
    connections:
        default:
            host:     '%env(RABBITMQ_HOST)%'
            port:     '%env(RABBITMQ_PORT)%'
            user:     '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost:    '/'
            lazy:     true
            connection_timeout: 300
            read_write_timeout: 300
            heartbeat: 150

    producers:
        add_event:
            connection:       default
            exchange_options: { name: 'add-event', type: direct }
            class:            App\Producer\EventProducer
        remove_image_thumbnails:
            connection:       default
            exchange_options: { name: 'remove-image-thumbnails', type: direct }
            class:            App\Producer\RemoveImageThumbnailsProducer
        purge_cdn_cache_urls:
            connection:       default
            exchange_options: { name: 'purge-cdn-cache-urls', type: direct }
            class:            App\Producer\PurgeCdnCacheUrlProducer

    batch_consumers:
        add_event:
            connection:       default
            exchange_options: { name: 'add-event', type: direct }
            queue_options:    { name: 'add-event'}
            callback:         App\Consumer\AddEventConsumer
            qos_options:      { prefetch_size: 0, prefetch_count: 50, global: false }
            timeout_wait:     300
            auto_setup_fabric: false
            idle_timeout_exit_code: -2

        remove_image_thumbnails:
            connection:       default
            exchange_options: { name: 'remove-image-thumbnails', type: direct }
            queue_options:    { name: 'remove-image-thumbnails'}
            callback:         App\Consumer\RemoveImageThumbnailsConsumer
            qos_options:      { prefetch_size: 0, prefetch_count: 5, global: false }
            auto_setup_fabric: false
            idle_timeout_exit_code: -2

        purge_cdn_cache_urls:
            connection:       default
            exchange_options: { name: 'purge-cdn-cache-urls', type: direct }
            queue_options:    { name: 'purge-cdn-cache-urls'}
            callback:         App\Consumer\PurgeCdnCacheUrlConsumer
            qos_options:      { prefetch_size: 0, prefetch_count: 30, global: false }
            auto_setup_fabric: false
            idle_timeout_exit_code: -2
