vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    storage: flysystem

    mappings:
        user_image:
            uri_prefix: /uploads/users
            upload_destination: users.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_property: createdAt

        event_image:
            uri_prefix: /uploads/documents
            upload_destination: events.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_property: createdAt
