services:
    app:
        volumes:
            - .:/app
            - /app/node_modules
            - /app/vendor
        env_file:
            - .env
            - .env.local

    worker:
        volumes:
            - .:/app
            - /app/node_modules
            - /app/vendor
