version: '3.4'

services:
    assets:
        volumes:
            - assets:/assets/build:ro
            - bundles:/assets/bundles:ro
        depends_on:
            - app

    app:
        environment:
            - BLACKFIRE_CLIENT_ID
            - BLACKFIRE_CLIENT_TOKEN
        depends_on:
            - elasticsearch
            - rabbitmq
            - redis
        ports:
            - 8030:80

    worker:
        container_name: worker
        command: ['worker']
        depends_on:
            - elasticsearch
            - rabbitmq
            - redis
            - app

    varnish:
        image: varnish:6.4
        command: ['varnishd', '-F', '-f', '/etc/varnish/default.vcl', '-t', '0']
        ports:
            - 8031:80
        tmpfs:
            - /usr/local/var/varnish
        depends_on:
            - app

volumes:
    assets:
    bundles:
    sitemap:
    storage:
