<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Agenda;
use Doctrine\ORM\EntityRepository;

/**
 * CalendrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierRepository extends EntityRepository
{
    public function getLastDateParticipation(Agenda $soiree)
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('MAX(c.lastDate)')
            ->from('AppBundle:Calendrier', "c")
            ->where("c.agenda = :agenda")
            ->setParameters([":agenda" => $soiree])
            ->getQuery()
            ->getSingleScalarResult();
    }
}
