<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ZipCity;

/**
 * ZipCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipCityRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string|null $postalCode
     * @param string|null $city
     * @param string $country
     * @return ZipCity[]
     */
    private function findByPostalCodeOrCity($postalCode, $city, $country) {
        $query = $this
            ->createQueryBuilder("zc")
            ->where("zc.country = :country")
            ->setParameter("country", $country);

        if($postalCode) {
            $query
                ->andWhere("zc.postalCode = :postalCode")
                ->setParameter("postalCode", $postalCode);
        }

        if($city) {
            $query
                ->andWhere("(zc.name = :city OR zc.name = :city_bis)")
                ->setParameter("city", $city)
                ->setParameter("city_bis", str_replace(" ", "-", $city));
        }

        return $query
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getResult();
    }

    /**
     * @param string $postalCode
     * @param string|null $city
     * @param string $country
     * @return ZipCity[]
     */
    public function findByPostalCodeAndCity($postalCode, $city, $country) {
        return $this->findByPostalCodeOrCity($postalCode, $city, $country);
    }

    /**
     * @param string|null $city
     * @param string $country
     * @return ZipCity[]
     */
    public function findByCity($city, $country) {
        return $this->findByPostalCodeOrCity(null, $city, $country);
    }

    /**
     * @param string $postalCode
     * @param string $country
     * @return ZipCity[]
     */
    public function findByPostalCode($postalCode, $country) {
        return $this->findByPostalCodeOrCity($postalCode, null, $country);
    }
}
