<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminZone1Repository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminZone1Repository extends EntityRepository
{
}
