<?php

namespace App\Repository;

/**
 * AdminZoneRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminZoneRepository extends \Doctrine\ORM\EntityRepository
{
}
