<?php

namespace AppBundle\Repository;

/**
 * AdminZone2Repository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminZone2Repository extends \Doctrine\ORM\EntityRepository
{
}
