<?php

namespace App\Repository;

use App\Entity\Event;
use Doctrine\ORM\EntityRepository;

/**
 * CalendrierRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierRepository extends EntityRepository
{
    public function getLastDateParticipation(Event $event)
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('MAX(c.lastDate)')
            ->from('App:Calendrier', 'c')
            ->where('c.event = :event')
            ->setParameters([':event' => $event])
            ->getQuery()
            ->getSingleScalarResult();
    }
}
