<?php

/*
 * This file is part of By Night.
 * (c) Guillaume Sainthillier <guillaume.sainthillier@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriqueMajRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueMajRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['id' => 'DESC']);
    }
}
