<?php

/*
 * This file is part of By Night.
 * (c) Guillaume Sainthillier <guillaume.sainthillier@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findNextEdition()
    {
        $result = $this
            ->createQueryBuilder('n')
            ->select('MAX (n.numeroEdition) AS nextEdition')
            ->getQuery()
            ->getSingleScalarResult();

        if (!$result) {
            return 1;
        }

        return (int) $result + 1;
    }
}
