<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * PlaceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    public function findSiteMap()
    {
        return $this->createQueryBuilder('p')
            ->select('p.slug, c.slug AS city_slug')
            ->join('p.city', 'c')
            ->getQuery()
            ->iterate();
    }

    public function findAllVilles()
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('p.ville')
            ->addSelect('s.id')
            ->from('App:Place', 'p')
            ->join('App:Site', 's', Expr\Join::WITH, 'p.site = s')
            ->where('p.ville IS NOT NULL')
            ->groupBy('p.ville')
            ->getQuery()
            ->getScalarResult();
    }

    public function findAllFBIds()
    {
        $places = $this->_em
            ->createQueryBuilder()
            ->select('p.facebookId')
            ->from('App:Place', 'p')
            ->where('p.facebookId IS NOT NULL')
            ->getQuery()
            ->getScalarResult();

        return \array_unique(\array_filter(\array_column($places, 'facebookId')));
    }
}
