<?php

namespace TBN\MajDataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlackListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlackListRepository extends EntityRepository
{
}
