<?php

namespace TBN\AgendaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * PlaceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    public function findAllVilles()
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('p.ville')
            ->addSelect('s.id')
            ->from('TBNAgendaBundle:Place', 'p')
            ->join('TBNMainBundle:Site', 's', Expr\Join::WITH, 'p.site = s')
            ->where('p.ville IS NOT NULL')
            ->groupBy('p.ville')
            ->getQuery()
            ->getScalarResult();
    }

    public function findAllFBIds()
    {
        $places = $this->_em
            ->createQueryBuilder()
            ->select('p.facebookId')
            ->from('TBNAgendaBundle:Place', 'p')
            ->where('p.facebookId IS NOT NULL')
            ->getQuery()
            ->getScalarResult();

        return array_unique(array_filter(array_column($places, 'facebookId')));
    }

    public function findAllCities()
    {
        $places = $this->_em
            ->createQueryBuilder()
            ->select('p.ville')
            ->from('TBNAgendaBundle:Place', 'p')
            ->where('p.ville IS NOT NULL')
            ->groupBy('p.ville')
            ->getQuery()
            ->getScalarResult();

        return array_unique(array_filter(array_column($places, 'ville')));
    }
}
