<?php

namespace TBN\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRepository extends EntityRepository
{
}
