<?php

namespace TBN\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use TBN\MainBundle\Entity\Site;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findTopMembres(Site $site, $page = 1, $limit = 7)
    {
        return $this->createQueryBuilder('u')
            ->select('u', 'i')
            ->leftJoin('u.info', 'i')
            ->where("u.site = :site")
            ->orderBy('u.lastLogin', 'DESC')
            ->setParameters([":site" => $site->getId()])
            ->setFirstResult(($page - 1) * $limit)
            ->setMaxResults($limit)
            ->getQuery()
            ->execute();
    }

    public function findMembresCount(Site $site)
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('count(u.id)')
            ->from('TBNUserBundle:User', 'u')
            ->where("u.site = :site")
            ->setParameters([":site" => $site->getId()])
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getLastDateUser(Site $site)
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('MAX(u.lastLogin)')
            ->from('TBNUserBundle:User', "u")
            ->where("u.site = :site")
            ->setParameters([":site" => $site->getId()])
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function search(Site $site, $term)
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('u')
            ->from('TBNUserBundle:User', "u")
            ->where("u.site = :site")
            ->andWhere("u.username LIKE :username")
            ->orderBy("u.username")
            ->setParameters([":site" => $site->getId(), ":username" => '%' . $term . '%'])
            ->getQuery()
            ->execute();
    }
}
