<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriqueMajRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueMajRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy([], ['id' => 'DESC']);
    }
}
