name: 'Continuous Integration'

on:
    pull_request:
    push:
        branches:
            - 'main'

jobs:
    matrix:
        name: Generate job matrix
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.matrix.outputs.matrix }}
        steps:
            - name: Gather CI configuration
              id: matrix
              uses: laminas/laminas-ci-matrix-action@v1

    qa:
        name: QA Checks
        needs: [matrix]
        runs-on: ${{ matrix.operatingSystem }}
        strategy:
            fail-fast: false
            matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
        steps:
            - name: ${{ matrix.name }}
              uses: laminas/laminas-continuous-integration-action@v1
              with:
                  job: ${{ matrix.job }}

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5'
                  extensions: amqp, redis
            - name: Install Composer dependencies
              run: composer install --no-interaction --no-progress --prefer-dist
            - name: Setup Node.js
              uses: actions/setup-node@v7
              with:
                  node-version: '24'
                  cache: 'yarn'
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Biome
              run: yarn lint-ci
            - name: Knip
              run: yarn knip

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Setup Node.js
              uses: actions/setup-node@v7
              with:
                  node-version: '24'
                  cache: 'yarn'
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Test
              run: yarn test

    ci-passed:
        name: CI passed
        needs: [matrix, qa, lint, test]
        if: always()
        runs-on: ubuntu-latest
        steps:
            - name: Check that all required jobs succeeded
              if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
              run: exit 1
